spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.0.103:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.0.103
    port: 6379
